TEMP

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -10,21 +10,21 @@ cache:
 script:
   - npm run build
 
-before-deploy:
-  - >
-    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
-      export BEFORE_DEPLOY_RUN=1;
-      npm run deploy-storybook -- -o site;
-    fi
+# before-deploy:
+#   - >
+#     if ! [ "$BEFORE_DEPLOY_RUN" ]; then
+#       export BEFORE_DEPLOY_RUN=1;
+#       npm run deploy-storybook -- -o site;
+#     fi
 
 deploy:
-  - provider: pages
-    edge: false
-    github_token: ${GITHUB_TOKEN}
-    local_dir: site
-    skip_cleanup: true
-    on:
-      all_branches: true
+  # - provider: pages
+  #   edge: false
+  #   github_token: ${GITHUB_TOKEN}
+  #   local_dir: site
+  #   skip_cleanup: true
+  #   on:
+  #     all_branches: true
   - provider: npm
     email: $NPM_EMAIL
     api_key: $NPM_API_KEY
